### ISSUE TITLE
Allow configurable registry url

### ISSUE THREAD

**Issue by WaleedAshraf** [herrmannplatz/npm-dependency-links#5]
Hi,

Can we allow to pass custom registry URL, like for verdaccio: https://www.verdaccio.org/ 

I think we need to update it [here](https://github.com/herrmannplatz/npm-dependency-links/blob/master/extension.js#L8
)
```javascript
const linkUri = Uri.parse(`https://www.npmjs.com/package/${package}`);
```

**Comment by herrmannplatz** [comment]
Awesome! Thanks for adding that. I thought about it some time ago since im also have to deal with a private registry at, but didnt had the insentive do start. Will check the PR later and merge it. 

While thinking about it im actually curious if we can resolve the url by checking the npmrc or package-lock/yarn lock. I had to work on project where some scoped packages where coming from a private registry while other came from the public npm registry.

**Comment by WaleedAshraf** [comment]
I was also thinking about reading from npmrc but that might be a bit tricky. Like, we use verdaccio so for us, npmrc is like
### Verdaccio
```
registry = "http://verdaccio.<our-custom-name>/"
```

But path packages on verdaccio is like
```
http://verdaccio.<our-custom-name>/#/detail/<package-name>
```

### For NPM
```
registry = "https://registry.npmjs.org/"
```
Path to package is:
```
https://www.npmjs.com/package/<package-name>
```

The registry is not used as it is for path to package. I'm not sure about other registries.
